# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: weatherapp.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10weatherapp.proto\x12\nweatherapp\"\x17\n\tIPRequest\x12\n\n\x02ip\x18\x01 \x01(\t\"H\n\rLocationReply\x12\x0b\n\x03lat\x18\x01 \x01(\x01\x12\x0b\n\x03lon\x18\x02 \x01(\x01\x12\x0c\n\x04\x63ity\x18\x03 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x04 \x01(\t\"*\n\x0eWeatherRequest\x12\x0b\n\x03lat\x18\x01 \x01(\x01\x12\x0b\n\x03lon\x18\x02 \x01(\x01\"Y\n\x0cWeatherReply\x12\x0c\n\x04time\x18\x01 \x01(\t\x12\x13\n\x0btemperature\x18\x02 \x01(\x01\x12\x11\n\twindspeed\x18\x03 \x01(\x01\x12\x13\n\x0bweathercode\x18\x04 \x01(\x05\x32L\n\x0bIP2Location\x12=\n\x07Resolve\x12\x15.weatherapp.IPRequest\x1a\x19.weatherapp.LocationReply\"\x00\x32L\n\x07Weather\x12\x41\n\x07\x43urrent\x12\x1a.weatherapp.WeatherRequest\x1a\x18.weatherapp.WeatherReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'weatherapp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IPREQUEST']._serialized_start=32
  _globals['_IPREQUEST']._serialized_end=55
  _globals['_LOCATIONREPLY']._serialized_start=57
  _globals['_LOCATIONREPLY']._serialized_end=129
  _globals['_WEATHERREQUEST']._serialized_start=131
  _globals['_WEATHERREQUEST']._serialized_end=173
  _globals['_WEATHERREPLY']._serialized_start=175
  _globals['_WEATHERREPLY']._serialized_end=264
  _globals['_IP2LOCATION']._serialized_start=266
  _globals['_IP2LOCATION']._serialized_end=342
  _globals['_WEATHER']._serialized_start=344
  _globals['_WEATHER']._serialized_end=420
# @@protoc_insertion_point(module_scope)
